# Generated by Django 5.1.4 on 2024-12-14 20:21

import base.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        validators=[base.validators.cpf_validator],
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("creation_date", models.DateField(auto_now_add=True)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=2,
                        validators=[
                            django.core.validators.MaxValueValidator(0.0),
                            django.core.validators.MinValueValidator(10.0),
                        ],
                    ),
                ),
            ],
        ),
    ]
