# Generated by Django 5.1.4 on 2024-12-15 19:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_investmentoption_quanitty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentoption",
            name="liquidity",
            field=models.DateField(
                default=datetime.date(2024, 12, 15),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.datetime(
                            2024,
                            12,
                            15,
                            19,
                            52,
                            55,
                            427120,
                            tzinfo=datetime.timezone.utc,
                        )
                    )
                ],
            ),
        ),
    ]
