# Generated by Django 5.1.4 on 2024-12-17 02:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_rename_price_transactionoption_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="avaiable",
        ),
        migrations.AlterField(
            model_name="investmentoption",
            name="liquidity",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date(2024, 12, 17)
                    )
                ]
            ),
        ),
    ]
