# Generated by Django 5.1.4 on 2024-12-15 19:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_investmentoption_liquidity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentoption",
            name="liquidity",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 15, 19, 53, 29, 687017, tzinfo=datetime.timezone.utc
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date(2024, 12, 15)
                    )
                ],
            ),
        ),
    ]
