# Generated by Django 5.1.4 on 2024-12-15 20:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_investmentoption_liquidity"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentoption",
            name="image",
            field=models.ImageField(default="aaaa", upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="investmentoption",
            name="liquidity",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 15, 20, 6, 51, 910543, tzinfo=datetime.timezone.utc
                ),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date(2024, 12, 15)
                    )
                ],
            ),
        ),
    ]
