# Generated by Django 5.1.4 on 2024-12-15 20:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_investmentoption_liquidity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentoption",
            name="liquidity",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date(2024, 12, 15)
                    )
                ]
            ),
        ),
    ]
