# Generated by Django 5.1.4 on 2024-12-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_investmentoption_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentoption",
            name="name",
            field=models.CharField(default="option", max_length=64),
            preserve_default=False,
        ),
    ]
