# Generated by Django 5.1.4 on 2024-12-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_investmentoption_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investmentoption",
            old_name="quanitty",
            new_name="quantity",
        ),
    ]
