# Generated by Django 5.1.4 on 2024-12-16 01:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_rename_quanitty_investmentoption_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                ("category", models.CharField(default="General", max_length=32)),
                (
                    "min_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="investmentoption",
            name="liquidity",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.date(2024, 12, 16)
                    )
                ]
            ),
        ),
    ]
